name: 🤖 Issue Automation
run-name: '🤖 [issue ${{ github.event.action }}] ${{ github.event.issue.title }}'
on:
  issues:
    types:
      - opened
      - assigned
      - unassigned
      - closed
      - reopened
      - field_added
permissions:
  issues: write
jobs:
  automate:
    uses: caret-collective/issue-automation/.github/workflows/issue-automations.yml@b8588ba5d36d633914980336d6cbdb0f900e636b
    secrets:
      project_token: ${{ secrets.ORG_PROJECT_TOKEN }}
